/**
 * Generates `src/iconData.ts` — the bundled MDI subset.
 *
 * Without this, `@iconify/vue`'s <Icon> resolves every name it hasn't seen by
 * calling out to api.iconify.design at runtime: a third-party round-trip on
 * first paint for core chrome, icons that pop in late, and nothing at all
 * rendered offline or behind a CSP that doesn't allow the host.
 *
 * The full `mdi` collection is 3 MB, so shipping it wholesale isn't an option.
 * Instead we scan the monorepo for `mdi:*` literals — which covers both the
 * IconPicker catalogue in src/icons.ts and every icon hardcoded in a template —
 * and emit just those. Scanning apps/ from packages/ui is a layering inversion,
 * but it's a build step in a private monorepo and the alternative (each app
 * registering its own subset) buys nothing here.
 *
 * Names outside the subset still render nothing rather than erroring, which is
 * exactly what an unresolvable name did before. Run via `npm run build-icons`;
 * the build and dev scripts do it for you.
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { dirname, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');

/** Source trees that may name an icon. */
const SCAN_ROOTS = [
  join(repoRoot, 'packages/ui/src'),
  join(repoRoot, 'apps/web/src'),
  join(repoRoot, 'apps/homepage/src'),
];

const SCAN_EXTS = new Set(['.ts', '.vue', '.js', '.json']);
const ICON_RE = /\bmdi:[a-z0-9]+(?:-[a-z0-9]+)*/g;

async function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else if (SCAN_EXTS.has(extname(entry.name))) out.push(full);
  }
  return out;
}

async function collectNames() {
  const names = new Set();
  for (const root of SCAN_ROOTS) {
    for (const file of await walk(root)) {
      // Skip the generated file itself, or every name stays pinned forever.
      if (file.endsWith('iconData.ts')) continue;
      const text = await readFile(file, 'utf8');
      for (const match of text.match(ICON_RE) ?? []) names.add(match.slice(4));
    }
  }
  return [...names].sort();
}

/**
 * Resolves a name to a concrete icon body, following alias chains. MDI ships
 * 6363 aliases, and several catalogue entries point at one.
 */
function resolve(collection, name, seen = new Set()) {
  if (collection.icons[name]) return { name, icon: collection.icons[name] };
  const alias = collection.aliases?.[name];
  if (!alias || seen.has(name)) return null;
  seen.add(name);
  return resolve(collection, alias.parent, seen);
}

const mdi = JSON.parse(
  await readFile(join(repoRoot, 'node_modules/@iconify-json/mdi/icons.json'), 'utf8'),
);

const wanted = await collectNames();
const icons = {};
const aliases = {};
const missing = [];

for (const name of wanted) {
  if (mdi.icons[name]) {
    icons[name] = mdi.icons[name];
    continue;
  }
  const resolved = resolve(mdi, name);
  if (!resolved) {
    missing.push(name);
    continue;
  }
  // Flatten the alias onto its resolved body so the runtime needs no chain.
  icons[resolved.name] = resolved.icon;
  aliases[name] = { parent: resolved.name };
}

if (missing.length > 0) {
  console.warn(
    `[build-icons] ${missing.length} name(s) do not exist in mdi and will render nothing:\n  ${missing.join('\n  ')}`,
  );
}

const subset = {
  prefix: mdi.prefix,
  icons,
  ...(Object.keys(aliases).length > 0 ? { aliases } : {}),
  width: mdi.width,
  height: mdi.height,
};

const out = `// GENERATED by scripts/build-icons.mjs — do not edit.
// ${Object.keys(icons).length} icons bundled from @iconify-json/mdi so <Icon>
// never calls api.iconify.design at runtime. Regenerate with: npm run build-icons
import type { IconifyJSON } from '@iconify/vue'

export const mdiSubset: IconifyJSON = ${JSON.stringify(subset)}
`;

const target = join(here, '..', 'src', 'iconData.ts');
await writeFile(target, out);

const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
console.log(
  `[build-icons] ${Object.keys(icons).length} icons + ${Object.keys(aliases).length} aliases → src/iconData.ts (${kb} KB)`,
);
