// Copies the wire contract into the SDK. packages/realtime is private to the
// monorepo, and a published package cannot depend on it. test/protocol.test.ts
// fails if the copy drifts.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const source = new URL('../../realtime/src/index.ts', import.meta.url);
const target = new URL('../src/protocol.ts', import.meta.url);

const HEADER =
  '// GENERATED by scripts/syncProtocol.mjs from packages/realtime/src/index.ts. Do not edit.\n\n';

const next = HEADER + readFileSync(source, 'utf8');
const current = existsSync(target) ? readFileSync(target, 'utf8') : null;

if (current !== next) {
  writeFileSync(target, next);
  console.log('protocol.ts updated from packages/realtime');
}
